--- a/.github/workflows/test_ollama.yml
+++ b/.github/workflows/test_ollama.yml
@@ -42,4 +42,4 @@
 
     - name: Test provider
       run: |
-        poetry run pytest -s -vv tests/test_providers.py::test_ollama
+        poetry run pytest -s -vv tests/test_providers.py::test_ollama